; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; handling multiple main files: https://community.platformio.org/t/here-is-a-simple-way-to-have-many-small-main-apps/26009
; uploading specific main file: pio run -t upload -e master

[env]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    SPI
    Wire
    https://github.com/nRF24/RF24.git
    https://github.com/nRF24/RF24Network.git
    https://bitbucket.org/teckel12/arduino-new-ping.git
    https://github.com/NorthernWidget/DS3231.git
build_src_filter =
    +<*.h>
    +<main_${PIOENV}.cpp>


[env:master]
board = megaatmega2560
[env:slave]
[env:controller]
board = megaatmega2560